# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-TransMetaphone
version:      0.07
version_from: lib/Text/TransMetaphone.pm
installdirs:  site
requires:
    Regexp::Ethiopic:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
